### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by koenderks** [jasp-stats/jaspIrt#3]
- [x] DIF (Koen), see https://github.com/jasp-stats/jaspIrt/pull/4
- [x] Boxje voor assen in ICC en IIC (Koen), see https://github.com/jasp-stats/jaspIrt/pull/4
- [ ] Multidimensional (confirmatory vs. exploratory)
- [ ] Convergence checks for Bayesian analyses
